# Site settings
title: aflyax-blog.github.io
email: aflyax@gmail.com
description: "Exploring data science with Julia and Python"
baseurl: ""
url: "https://aflyax-blog.github.io"
twitter_username: lauriswat
github_username:  lauris

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap